name: Hierarchy build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { name: hierarchy-app, platform: linux/amd64, os: ubuntu-latest },
            {
              name: hierarchy-app,
              platform: windows/amd64,
              os: windows-latest,
            },
            {
              name: hierarchy-app,
              platform: darwin/universal,
              os: macos-latest,
            },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v3
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
